// <auto-generated />
using System;
using ClassroomService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassroomService.Infrastructure.Migrations
{
    [DbContext(typeof(ClassroomDbContext))]
    [Migration("20251211090000_AddAuditFieldsToConversationCrawlData")]
    partial class AddAuditFieldsToConversationCrawlData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // NOTE: This is a simplified Designer file showing only the ConversationCrawlData entity changes.
            // In a real scenario, EF Core would generate the full model here.
            // Since we're manually creating this migration, we only document the affected entity.

            modelBuilder.Entity("ClassroomService.Domain.Entities.ConversationCrawlData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrawlJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DataQualityScore")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetectedSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvalidRecordCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    // NEW: Audit fields from BaseAuditableEntity
                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ValidRecordCount")
                        .HasColumnType("int");

                    b.Property<string>("ValidationWarningsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VectorEmbeddingJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CrawlJobId")
                        .IsUnique();

                    b.HasIndex("DataQualityScore");

                    b.HasIndex("ConversationId", "CrawledAt");

                    b.ToTable("ConversationCrawlData");
                });
#pragma warning restore 612, 618
        }
    }
}
