// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCrawlerService.Infrastructure.Contexts;

#nullable disable

namespace WebCrawlerService.Infrastructure.Migrations
{
    [DbContext(typeof(CrawlerDbContext))]
    [Migration("20251017143812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoSolveCaptcha")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("CrawlerAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CrawlerPreference")
                        .HasColumnType("int");

                    b.Property<int>("CrawlerType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("ExtractImages")
                        .HasColumnType("bit");

                    b.Property<bool>("ExtractLinks")
                        .HasColumnType("bit");

                    b.Property<string>("ExtractionStrategyJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FollowRedirects")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<long>("TotalContentSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Urls")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("UrlsFailed")
                        .HasColumnType("int");

                    b.Property<int>("UrlsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("UrlsSuccessful")
                        .HasColumnType("int");

                    b.Property<bool>("UseProxyRotation")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("CrawlerAgentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("CrawlJobs");
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisResultId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CaptchaCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CaptchasSolved")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ContentSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CrawlJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedDataJson")
                        .HasColumnType("text");

                    b.Property<double>("ExtractionConfidence")
                        .HasColumnType("float");

                    b.Property<string>("ExtractionWarnings")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("LlmCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PromptUsed")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("ProxyUsed")
                        .HasColumnType("bit");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<string>("ScreenshotBase64")
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("CrawlJobId");

                    b.HasIndex("CrawledAt");

                    b.HasIndex("Url");

                    b.ToTable("CrawlResults");
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiEndpointPattern")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AverageExtractionTimeMs")
                        .HasColumnType("int");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeprecatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DomainPattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemTemplate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastValidationError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MobileApiConfigJson")
                        .HasColumnType("text");

                    b.Property<int?>("MobileApiProvider")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RateLimitDelayMs")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedCrawler")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresAuthentication")
                        .HasColumnType("bit");

                    b.Property<string>("SampleUrls")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("float");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DomainPattern");

                    b.HasIndex("IsActive");

                    b.HasIndex("MobileApiProvider");

                    b.HasIndex("PreviousVersionId");

                    b.HasIndex("Type");

                    b.ToTable("CrawlTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            ApiEndpointPattern = "/api/v4/item/get?itemid={itemId}&shopid={shopId}",
                            AverageExtractionTimeMs = 0,
                            ConfigurationJson = "{\"selectors\":{\"productName\":[\"h1.product-title\",\".product-name\",\"#product-name\"],\"price\":[\".product-price\",\"[data-price]\",\".price-text\"],\"originalPrice\":[\".original-price\",\".old-price\"],\"rating\":[\".product-rating\",\"[data-rating]\"],\"stock\":[\".stock-quantity\",\"[data-stock]\"],\"sold\":[\".sold-count\",\"[data-sold]\"],\"description\":[\".product-description\",\".description-content\"],\"images\":[\".product-image img\",\".gallery-image\"]},\"dynamicSelectors\":{},\"requiresJavaScript\":false,\"scrollToBottom\":false,\"waitForSelectors\":[\".product-title\",\".product-price\"],\"confidence\":0.95,\"estimatedTimeSeconds\":2}",
                            CreatedAt = new DateTime(2025, 10, 17, 14, 38, 11, 655, DateTimeKind.Utc).AddTicks(7758),
                            Description = "Extract product information from Shopee product pages including price, rating, specifications, and reviews summary",
                            DomainPattern = "*.shopee.vn/product/*,*.shopee.vn/*-i.*.*",
                            IsActive = true,
                            IsPublic = true,
                            IsSystemTemplate = true,
                            IsValidated = true,
                            LastTestedAt = new DateTime(2025, 10, 17, 14, 38, 11, 655, DateTimeKind.Utc).AddTicks(7748),
                            MobileApiConfigJson = "{\"Provider\":0,\"BaseUrl\":\"https://shopee.vn\",\"ApiVersion\":\"v4\",\"RequiredHeaders\":{\"User-Agent\":\"Shopee/2.98.21 Android/11\",\"X-API-Source\":\"pc\",\"X-Shopee-Language\":\"vi\",\"Accept\":\"application/json\"},\"DefaultParams\":{},\"SignatureAlgorithm\":null,\"RequiresSignature\":false,\"RequiresCookies\":false,\"Region\":\"VN\",\"RateLimitPerMinute\":20,\"RequiresProxy\":false}",
                            MobileApiProvider = 0,
                            Name = "Shopee Product Page",
                            RateLimitDelayMs = 500,
                            RecommendedCrawler = 5,
                            RequiresAuthentication = false,
                            SampleUrls = "https://shopee.vn/Ch%C4%83n-cotton-%C4%91%C5%A9i-3-l%E1%BB%9Bp-1m8x2m-m%E1%BB%81m-m%E1%BB%8Bn-ch%C4%83n-%C4%91%C5%A9i-x%C6%A1-%C4%91%E1%BA%ADu-l%C3%A0nh-i.29708084.23984073012;https://shopee.vn/product-example-i.123456.789012",
                            SuccessRate = 0.0,
                            Tags = "shopee,product,ecommerce,vietnam,mobile-api",
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 10, 17, 14, 38, 11, 655, DateTimeKind.Utc).AddTicks(7758),
                            UsageCount = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            ApiEndpointPattern = "/api/v4/item/get_ratings?itemid={itemId}&shopid={shopId}&limit={limit}&offset={offset}",
                            AverageExtractionTimeMs = 0,
                            ConfigurationJson = "{\"pagination\":{\"enabled\":true,\"limitPerPage\":20,\"maxPages\":50,\"offsetParameter\":\"offset\"},\"selectors\":{\"reviewText\":[\".review-comment\",\".comment-text\"],\"rating\":[\".review-rating\",\"[data-rating]\"],\"reviewerName\":[\".reviewer-name\",\".user-name\"],\"reviewDate\":[\".review-date\",\"[data-date]\"],\"helpful\":[\".helpful-count\",\"[data-helpful]\"],\"images\":[\".review-image img\"]},\"filters\":{\"all\":0,\"withComment\":1,\"withImage\":2,\"fiveStar\":5,\"fourStar\":4,\"threeStar\":3,\"twoStar\":2,\"oneStar\":1},\"confidence\":0.9,\"estimatedTimeSeconds\":3}",
                            CreatedAt = new DateTime(2025, 10, 17, 14, 38, 11, 655, DateTimeKind.Utc).AddTicks(8332),
                            Description = "Extract user reviews and ratings from Shopee products with pagination support",
                            DomainPattern = "*.shopee.vn/product/*,*.shopee.vn/*-i.*.*",
                            IsActive = true,
                            IsPublic = true,
                            IsSystemTemplate = true,
                            IsValidated = true,
                            LastTestedAt = new DateTime(2025, 10, 17, 14, 38, 11, 655, DateTimeKind.Utc).AddTicks(8329),
                            MobileApiConfigJson = "{\"Provider\":0,\"BaseUrl\":\"https://shopee.vn\",\"ApiVersion\":\"v4\",\"RequiredHeaders\":{\"User-Agent\":\"Shopee/2.98.21 Android/11\",\"X-API-Source\":\"pc\",\"X-Shopee-Language\":\"vi\",\"Accept\":\"application/json\"},\"DefaultParams\":{},\"SignatureAlgorithm\":null,\"RequiresSignature\":false,\"RequiresCookies\":false,\"Region\":\"VN\",\"RateLimitPerMinute\":20,\"RequiresProxy\":false}",
                            MobileApiProvider = 0,
                            Name = "Shopee Product Reviews",
                            RateLimitDelayMs = 500,
                            RecommendedCrawler = 5,
                            RequiresAuthentication = false,
                            SampleUrls = "https://shopee.vn/Ch%C4%83n-cotton-%C4%91%C5%A9i-3-l%E1%BB%9Bp-1m8x2m-m%E1%BB%81m-m%E1%BB%8Bn-ch%C4%83n-%C4%91%C5%A9i-x%C6%A1-%C4%91%E1%BA%ADu-l%C3%A0nh-i.29708084.23984073012",
                            SuccessRate = 0.0,
                            Tags = "shopee,reviews,ratings,feedback,mobile-api",
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 10, 17, 14, 38, 11, 655, DateTimeKind.Utc).AddTicks(8332),
                            UsageCount = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            ApiEndpointPattern = "/api/v4/search/search_items?keyword={keyword}&limit={limit}&offset={offset}",
                            AverageExtractionTimeMs = 0,
                            ConfigurationJson = "{\"pagination\":{\"enabled\":true,\"limitPerPage\":60,\"maxPages\":20,\"offsetParameter\":\"offset\"},\"selectors\":{\"items\":[\".search-result-item\",\".product-item\"],\"productName\":[\".product-title\",\".item-name\"],\"price\":[\".product-price\",\"[data-price]\"],\"sold\":[\".sold-count\",\"[data-sold]\"],\"rating\":[\".product-rating\"],\"shopName\":[\".shop-name\"],\"productUrl\":[\"a[href*=\\u0027-i.\\u0027]\"]},\"sortOptions\":{\"relevancy\":\"relevancy\",\"sales\":\"sales\",\"price_asc\":\"price\",\"price_desc\":\"price_desc\",\"latest\":\"ctime\"},\"confidence\":0.85,\"estimatedTimeSeconds\":2}",
                            CreatedAt = new DateTime(2025, 10, 17, 14, 38, 11, 655, DateTimeKind.Utc).AddTicks(9035),
                            Description = "Search for products on Shopee by keyword with filtering and sorting options",
                            DomainPattern = "*.shopee.vn/search*,*.shopee.vn/api/v4/search/*",
                            IsActive = true,
                            IsPublic = true,
                            IsSystemTemplate = true,
                            IsValidated = true,
                            LastTestedAt = new DateTime(2025, 10, 17, 14, 38, 11, 655, DateTimeKind.Utc).AddTicks(9031),
                            MobileApiConfigJson = "{\"Provider\":0,\"BaseUrl\":\"https://shopee.vn\",\"ApiVersion\":\"v4\",\"RequiredHeaders\":{\"User-Agent\":\"Shopee/2.98.21 Android/11\",\"X-API-Source\":\"pc\",\"X-Shopee-Language\":\"vi\",\"Accept\":\"application/json\"},\"DefaultParams\":{},\"SignatureAlgorithm\":null,\"RequiresSignature\":false,\"RequiresCookies\":false,\"Region\":\"VN\",\"RateLimitPerMinute\":20,\"RequiresProxy\":false}",
                            MobileApiProvider = 0,
                            Name = "Shopee Product Search",
                            RateLimitDelayMs = 500,
                            RecommendedCrawler = 5,
                            RequiresAuthentication = false,
                            SampleUrls = "https://shopee.vn/search?keyword=laptop;https://shopee.vn/search?keyword=dien%20thoai",
                            SuccessRate = 0.0,
                            Tags = "shopee,search,discovery,listing,mobile-api",
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 10, 17, 14, 38, 11, 655, DateTimeKind.Utc).AddTicks(9036),
                            UsageCount = 0,
                            Version = 1
                        });
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlerAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageProcessingTime")
                        .HasColumnType("float");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentJobCount")
                        .HasColumnType("int");

                    b.Property<int>("FailedJobs")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxConcurrentJobs")
                        .HasColumnType("int");

                    b.Property<int>("MaxCpuPercent")
                        .HasColumnType("int");

                    b.Property<int>("MaxMemoryMB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SuccessfulJobs")
                        .HasColumnType("int");

                    b.Property<int>("TotalJobsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("CrawlerAgents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AverageProcessingTime = 0.0,
                            ConfigurationJson = "{\n                    \"provider\": \"Shopee\",\n                    \"apiVersion\": \"v4\",\n                    \"baseUrl\": \"https://shopee.vn\",\n                    \"supportedDomains\": [\"shopee.vn\", \"shopee.com\"],\n                    \"capabilities\": [\n                        \"product_details\",\n                        \"reviews\",\n                        \"ratings\",\n                        \"shop_info\",\n                        \"mobile_api\",\n                        \"high_speed\"\n                    ],\n                    \"features\": {\n                        \"productDetails\": true,\n                        \"reviews\": true,\n                        \"search\": true,\n                        \"shopInfo\": true\n                    },\n                    \"rateLimit\": {\n                        \"requestsPerMinute\": 20,\n                        \"burstSize\": 5\n                    },\n                    \"retry\": {\n                        \"maxAttempts\": 3,\n                        \"backoffMs\": 1000\n                    }\n                }",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentJobCount = 0,
                            FailedJobs = 0,
                            MaxConcurrentJobs = 5,
                            MaxCpuPercent = 50,
                            MaxMemoryMB = 256,
                            Name = "Shopee API Agent",
                            Status = 0,
                            SuccessfulJobs = 0,
                            TotalJobsProcessed = 0,
                            Type = 5,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserAgent = "Shopee/2.98.21 Android/11"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AverageProcessingTime = 0.0,
                            ConfigurationJson = "{\n                    \"capabilities\": [\n                        \"html_parsing\",\n                        \"static_content\",\n                        \"api_calls\",\n                        \"headers_manipulation\",\n                        \"cookies\"\n                    ],\n                    \"timeout\": 30000,\n                    \"followRedirects\": true,\n                    \"maxRedirects\": 5,\n                    \"compression\": true,\n                    \"retry\": {\n                        \"maxAttempts\": 3,\n                        \"backoffMs\": 2000\n                    }\n                }",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentJobCount = 0,
                            FailedJobs = 0,
                            MaxConcurrentJobs = 10,
                            MaxCpuPercent = 40,
                            MaxMemoryMB = 128,
                            Name = "HTTP Client Agent",
                            Status = 0,
                            SuccessfulJobs = 0,
                            TotalJobsProcessed = 0,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AverageProcessingTime = 0.0,
                            ConfigurationJson = "{\n                    \"capabilities\": [\n                        \"javascript_execution\",\n                        \"spa_support\",\n                        \"screenshots\",\n                        \"pdf_generation\",\n                        \"user_interactions\",\n                        \"network_interception\",\n                        \"geolocation\",\n                        \"device_emulation\"\n                    ],\n                    \"browser\": \"chromium\",\n                    \"headless\": true,\n                    \"viewport\": {\n                        \"width\": 1920,\n                        \"height\": 1080\n                    },\n                    \"timeout\": 60000,\n                    \"waitUntil\": \"networkidle\",\n                    \"blockResources\": [\"image\", \"font\", \"media\"],\n                    \"retry\": {\n                        \"maxAttempts\": 2,\n                        \"backoffMs\": 5000\n                    }\n                }",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentJobCount = 0,
                            FailedJobs = 0,
                            MaxConcurrentJobs = 3,
                            MaxCpuPercent = 80,
                            MaxMemoryMB = 1024,
                            Name = "Playwright Browser Agent",
                            Status = 0,
                            SuccessfulJobs = 0,
                            TotalJobsProcessed = 0,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                        });
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.DomainPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DelayBetweenRequestsMs")
                        .HasColumnType("int");

                    b.Property<string>("DomainPattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxConcurrentRequests")
                        .HasColumnType("int");

                    b.Property<int?>("MaxRequestsPerMinute")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumTierRequired")
                        .HasColumnType("int");

                    b.Property<int>("PolicyType")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PolicyType");

                    b.ToTable("DomainPolicies");
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOnUtc");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("ProcessedOnUtc", "NextRetryAtUtc", "RetryCount");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlJob", b =>
                {
                    b.HasOne("WebCrawlerService.Domain.Entities.CrawlerAgent", "AssignedAgent")
                        .WithMany("AssignedJobs")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebCrawlerService.Domain.Entities.CrawlerAgent", null)
                        .WithMany("ActiveJobs")
                        .HasForeignKey("CrawlerAgentId");

                    b.HasOne("WebCrawlerService.Domain.Entities.CrawlTemplate", "Template")
                        .WithMany("CrawlJobs")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedAgent");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlResult", b =>
                {
                    b.HasOne("WebCrawlerService.Domain.Entities.CrawlJob", "CrawlJob")
                        .WithMany("Results")
                        .HasForeignKey("CrawlJobId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CrawlJob");
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlTemplate", b =>
                {
                    b.HasOne("WebCrawlerService.Domain.Entities.CrawlTemplate", "PreviousVersion")
                        .WithMany("NewerVersions")
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PreviousVersion");
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlJob", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlTemplate", b =>
                {
                    b.Navigation("CrawlJobs");

                    b.Navigation("NewerVersions");
                });

            modelBuilder.Entity("WebCrawlerService.Domain.Entities.CrawlerAgent", b =>
                {
                    b.Navigation("ActiveJobs");

                    b.Navigation("AssignedJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
