namespace WebCrawlerService.Domain.Models
{
    /// <summary>
    /// Result of executing a complete crawl job
    /// </summary>
    public class CrawlJobResult
    {
        public Guid JobId { get; set; }
        public bool Success { get; set; }
        public int ResultCount { get; set; }
        public double ExecutionTimeMs { get; set; }
        public string? ErrorMessage { get; set; }
        public int? FailedStep { get; set; }
        public string? PageSnapshot { get; set; }
        
        /// <summary>
        /// AI-generated conversation name from the user's prompt (generated by Python/Gemini)
        /// </summary>
        public string? ConversationName { get; set; }
    }
}
