namespace WebCrawlerService.Domain.Models;

/// <summary>
/// AI-generated strategy for data extraction
/// </summary>
public class ExtractionStrategy
{
    /// <summary>
    /// Fields to extract from the page
    /// </summary>
    public List<FieldDefinition> Fields { get; set; } = new();

    /// <summary>
    /// Dynamic CSS/XPath selectors generated by AI
    /// </summary>
    public Dictionary<string, string[]> DynamicSelectors { get; set; } = new();

    /// <summary>
    /// Whether JavaScript execution is required
    /// </summary>
    public bool RequiresJavaScript { get; set; }

    /// <summary>
    /// Whether to scroll to bottom of page
    /// </summary>
    public bool ScrollToBottom { get; set; }

    /// <summary>
    /// Selectors to wait for before extraction
    /// </summary>
    public string[] WaitForSelectors { get; set; } = Array.Empty<string>();

    /// <summary>
    /// Confidence score of the strategy (0.0 to 1.0)
    /// </summary>
    public double Confidence { get; set; }

    /// <summary>
    /// Estimated extraction time in seconds
    /// </summary>
    public int EstimatedTimeSeconds { get; set; }

    /// <summary>
    /// Any warnings or limitations
    /// </summary>
    public string[]? Warnings { get; set; }
}

/// <summary>
/// Definition of a field to extract
/// </summary>
public class FieldDefinition
{
    /// <summary>
    /// Field name (e.g., "productName", "price")
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Data type (text, number, currency, date, url, etc.)
    /// </summary>
    public string Type { get; set; } = "text";

    /// <summary>
    /// Whether this field is required
    /// </summary>
    public bool Required { get; set; }

    /// <summary>
    /// Ordered list of selectors to try (fallback mechanism)
    /// </summary>
    public string[] Selectors { get; set; } = Array.Empty<string>();

    /// <summary>
    /// Extraction method (text, html, attribute)
    /// </summary>
    public string ExtractionMethod { get; set; } = "text";

    /// <summary>
    /// Attribute name if extractionMethod is "attribute"
    /// </summary>
    public string? AttributeName { get; set; }

    /// <summary>
    /// Post-processing rules (trim, lowercase, regex, etc.)
    /// </summary>
    public string[]? PostProcessing { get; set; }
}
