namespace ClassroomService.Domain.Events;

/// <summary>
/// Event published to Kafka when a student initiates a smart crawl from the chat interface.
/// This event is consumed by WebCrawlerService to process the crawl request asynchronously.
/// </summary>
public class SmartCrawlRequestEvent
{
    /// <summary>
    /// Unique identifier for the crawl job (generated by ClassroomService)
    /// </summary>
    public Guid JobId { get; set; }

    /// <summary>
    /// Conversation ID for threading messages in the chat
    /// </summary>
    public Guid ConversationId { get; set; }

    /// <summary>
    /// Assignment this crawl belongs to
    /// </summary>
    public Guid AssignmentId { get; set; }

    /// <summary>
    /// Group this crawl belongs to (null for individual assignments)
    /// </summary>
    public Guid? GroupId { get; set; }

    /// <summary>
    /// User who initiated the crawl
    /// </summary>
    public Guid SenderId { get; set; }

    /// <summary>
    /// Name of the sender (for display purposes)
    /// </summary>
    public string SenderName { get; set; } = string.Empty;

    /// <summary>
    /// Target URL to crawl
    /// </summary>
    public string Url { get; set; } = string.Empty;

    /// <summary>
    /// Natural language instruction for the AI crawler
    /// </summary>
    public string UserPrompt { get; set; } = string.Empty;

    /// <summary>
    /// Maximum number of pages to crawl (pagination limit).
    /// Null means UI field was empty (use prompt extraction or default 50).
    /// </summary>
    public int? MaxPages { get; set; }

    /// <summary>
    /// Enable LLM-powered navigation planning
    /// </summary>
    public bool EnableNavigationPlanning { get; set; } = true;

    /// <summary>
    /// Timestamp when the request was created
    /// </summary>
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Additional metadata as JSON (for extensibility)
    /// </summary>
    public string? MetadataJson { get; set; }
}
