using System.Text.Json.Serialization;

namespace WebCrawlerService.Domain.Models.Crawl4AI;

/// <summary>
/// Response from crawl4ai intelligent crawl
/// </summary>
public class Crawl4AIResponse
{
    /// <summary>
    /// Whether the crawl succeeded
    /// </summary>
    [JsonPropertyName("success")]
    public bool Success { get; set; }

    /// <summary>
    /// Extracted data items
    /// </summary>
    [JsonPropertyName("data")]
    public List<Dictionary<string, object>> Data { get; set; } = new();

    /// <summary>
    /// Navigation result details (optional - may be null if no navigation occurred)
    /// </summary>
    [JsonPropertyName("navigation_result")]
    public NavigationResult? NavigationResult { get; set; }

    /// <summary>
    /// Execution time in milliseconds
    /// </summary>
    [JsonPropertyName("execution_time_ms")]
    public double ExecutionTimeMs { get; set; }

    /// <summary>
    /// AI-generated conversation name from the user's prompt (generated by Python agent)
    /// </summary>
    [JsonPropertyName("conversation_name")]
    public string? ConversationName { get; set; }

    /// <summary>
    /// Error message if failed
    /// </summary>
    [JsonPropertyName("error")]
    public string? Error { get; set; }
}

/// <summary>
/// Result of navigation execution
/// </summary>
public class NavigationResult
{
    /// <summary>
    /// Final URL after navigation
    /// </summary>
    [JsonPropertyName("final_url")]
    public string FinalUrl { get; set; } = null!;

    /// <summary>
    /// Steps that were executed
    /// </summary>
    [JsonPropertyName("executed_steps")]
    public List<Dictionary<string, object>> ExecutedSteps { get; set; } = new();

    /// <summary>
    /// Number of pages collected (pagination)
    /// </summary>
    [JsonPropertyName("pages_collected")]
    public int PagesCollected { get; set; }
}
